apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: rh-waterford-et-all-tt
spec:
  params:
  - name: repo
    default: ""
  - name: branch
    default: ""
  - name: pr
    default: ""
  - name: commit-sha
    default: ""
  - name: clean
    default: "true"
  resourcetemplates:
  - apiVersion: tekton.dev/v1beta1
    kind: PipelineRun
    metadata:
      generateName: rh-waterford-et-pipelinerun-
      annotations:
        operator.tekton.dev/prune.skip: "false"
        operator.tekton.dev/prune.resources: "taskrun, pipelinerun"
        operator.tekton.dev/prune.keep: "1"
        operator.tekton.dev/prune.strategy: "keep"
    spec:
      serviceAccountName: pipeline
      params:
        - name: repo
          value: $(tt.params.repo)
        - name: branch
          value: $(tt.params.branch)
        - name: pr
          value: $(tt.params.pr)
        - name: commit-sha
          value: $(tt.params.commit-sha)
        - name: clean
          value: "true"
      pipelineRef:
        name: rh-waterford-et-all
      timeouts:
        pipeline: "1h0m0s"
        tasks: "10m"
      workspaces:
        - name: cache
          persistentVolumeClaim:
            claimName: rh-wat-et-pvc01
        - name: go-build
          persistentVolumeClaim:
            claimName: rh-wat-et-pvc01 
        - name: shared-workspace
          persistentVolumeClaim:
            claimName: rh-wat-et-pvc01
