apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: rh-waterford-et-all-pipelinerun-
  annotations:
    operator.tekton.dev/prune.skip: "false"
    operator.tekton.dev/prune.resources: "taskrun, pipelinerun"
    operator.tekton.dev/prune.keep: "1"
    operator.tekton.dev/prune.strategy: "keep"
spec:
  params:
    - name: repo
      value: "https://github.com/openshift/os.git"
    - name: branch
      value: "release-4.13"
    - name: variant
      value: "scos"     
    - name: version
      value: "4.13"
  pipelineRef:
    name: rh-waterford-all
  timeouts:
    pipeline: "1h0m0s"
  workspaces:
    - name: cache
    - name: go-build
    - name: shared-workspace
      volumeClaimTemplate:
        spec:
          accessModes: 
            - ReadWriteOnce
          resources:
            requests:
              storage: 5Gi
