apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: rh-waterford-et-all
spec:
  params:
    - default: "none"
      name: repo
      type: string
    - default: "none"
      name: branch
      type: string
    - default: ""
      name: commit-sha
      type: string
    - default: ""
      name: pr
      type: string
    - default: "true"
      name: clean
      type: string
  tasks:
    - name: clone-repo
      params:
        - name: repo
          value: $(params.repo)
        - name: branch
          value: $(params.branch)
        - name: commit-sha
          value: $(params.commit-sha)
        - name: pr
          value: $(params.pr)
        - name: clean
          value: $(params.clean)
      taskRef:
        kind: Task
        name: clone-repo
      workspaces:
        - name: ws
          workspace: shared-workspace
    - name: lint
      runAfter:
        - clone-repo
      taskRef:
        kind: Task
        name: lint-repo
      params:
        - name: repo
          value: $(params.repo)
      workspaces:
        - name: ws
          workspace: shared-workspace
        - name: cache
          workspace: cache
    - name: build
      params:
        - name: repo
          value: $(params.repo)
      runAfter:
        - lint
      taskRef:
        kind: Task
        name: build-repo
      workspaces:
        - name: ws
          workspace: shared-workspace
        - name: cache
          workspace: cache
  finally:
    - name: report-pipeline-failed-to-github
      when:
        - input: $(tasks.status)
          operator: in
          values: [ "Failed", "None" ] 
      taskRef:
        name: "github-set-status"
      params:
        - name: status
          value: "failed"
        - name: repo
          value: "$(params.repo)"
        - name: commit-sha
          value: "$(params.commit-sha)"
      workspaces:
        - name: ws
          workspace: shared-workspace
    - name: report-pipeline-success-to-github
      when:
          - input: $(tasks.status)
            operator: in
            values: [ "Succeeded", "Completed" ] 
      taskRef:
        name: "github-set-status"
      params:
        - name: status
          value: "success"
        - name: repo
          value: "$(params.repo)"
        - name: commit-sha
          value: "$(params.commit-sha)"
      workspaces:
        - name: ws
          workspace: shared-workspace

  workspaces:
    - name: cache
    - name: go-build
    - name: shared-workspace
