---
kind: Pod
apiVersion: v1
metadata:
  name: debug-pod
  namespace: okd-team
spec:
  containers:
    - name: debug-pod
      image: docker.io/curlimages/curl:7.70.0@sha256:031df77a11e5edded840bc761a845eab6e3c2edee22669fb8ad6d59484b6a1c4
      script: |
        #!/bin/bash
        /usr/bin/curl -v -H "Content-type: application/json" -d '{"version":"4.13", "rpm-artifacts-image":"registry.ci.openshift.org/origin/4.13:artifacts", "tag-latest":"false", "claimname":"pipeline-scos-stable-pvc"}' "http://el-okd-coreos-all.okd-team.svc.cluster.local:8080"
