apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rh-waterford-et-pvc
  namespace: rh-waterford-et
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: nfs-ocp-rh-client
