apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rh-wat-et-pvc01
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5G
  storageClassName: nfs-ocp-rh-client
