apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/core/v1/
  - ../../base/tekton.dev/pipelines/
  - ../../base/tekton.dev/tasks/
  - ../../base/triggers.tekton.dev/eventlisteners/
  - ../../base/triggers.tekton.dev/triggerbindings/
  - ../../base/triggers.tekton.dev/triggertemplates/
namespace: rh-waterford-et
