apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: clone-repo
spec:
  params:
    - name: repo
      default: ""
      type: string
    - name: branch
      default: "none"
      type: string
    - name: pr
      default: "pr"
      type: string
    - name: commit-sha
      default: ""
      type: string
    - name: clean
      default: "true"
      type: string

  steps:
    - image: 'quay.io/luzuccar/rh-waterford-golang:v1.24.5'
      name: clone-repo
      resources:
        limits:
          cpu: 500m
          memory: 1Gi
        requests:
          cpu: 500m
          memory: 1Gi
      script: |
        #!/usr/bin/env bash
        # set -euxo pipefail
    
        cd /home/1001/src

        echo -e "repo   : $(params.repo)"
        echo -e "branch : $(params.branch)"
        echo -e "sha    : $(params.commit-sha)"
        echo -e "pr     : $(params.pr)"

        REPO_NAME=$(echo -e "$(params.repo)" | rev | cut -d/ -f1 | rev | cut -d. -f1)
        echo -e "${REPO_NAME}"
        ID=$(echo -e "$(params.pr)" | rev | cut -d/ -f1 | rev | cut -d. -f1)
        echo -e "${ID}"
        BRANCH_NAME=$(echo -e  "$(params.branch)-openshift-pipeline")
        rm -rf ${REPO_NAME}

        git clone -b main $(params.repo)
        
        cd ${REPO_NAME}
        git fetch origin pull/${ID}/head:${BRANCH_NAME}
        git checkout ${BRANCH_NAME}

      volumeMounts:
        - name: $(workspaces.ws.volume)
          mountPath: /home/1001/src
        
  workspaces:
    - mountPath: /src
      name: ws
