apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: pipelinerun-
  annotations:
    operator.tekton.dev/prune.skip: "false"
    operator.tekton.dev/prune.resources: "taskrun, pipelinerun"
    operator.tekton.dev/prune.keep: "1"
    operator.tekton.dev/prune.strategy: "keep"
spec:
  params:
    - name: repo
      value: "https://github.com/lmzuccarelli/p2code_scheduler_operator.git"
    - name: branch-name
      value: "testbranch"
    - name: "id"
      value: "1"
    - name: clean
      value: "true"
  pipelineRef:
    name: rh-waterford-et-all
  podTemplate:
    nodeSelector:
       kubernetes.io/os: linux
  timeouts:
    pipeline: "1h0m0s"
    tasks: "10m"
  #serviceAccountName: sa-okd-privileged
  workspaces:
    - name: shared-workspace
      persistentVolumeClaim:
        claimName: rh-wat-et-pvc01
    - name: cache
      persistentVolumeClaim:
        claimName: rh-wat-et-pvc01
    - name: go-build
      persistentVolumeClaim:
        claimName: rh-wat-et-pvc01
